<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AvancementsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('avancements')->delete();
        
        \DB::table('avancements')->insert(array (
            0 => 
            array (
                'id' => 1,
                'date' => '2026-08-01',
                'nombre_heure' => '2',
                'objectif_general' => 'OG1',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '10:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:18:13',
                'updated_at' => '2026-09-20 16:18:13',
            ),
            1 => 
            array (
                'id' => 2,
                'date' => '2026-08-08',
                'nombre_heure' => '2',
                'objectif_general' => 'OG2',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '10:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:18:48',
                'updated_at' => '2026-09-20 16:18:48',
            ),
            2 => 
            array (
                'id' => 3,
                'date' => '2026-08-15',
                'nombre_heure' => '2',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '10:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:19:31',
                'updated_at' => '2026-09-20 16:19:31',
            ),
            3 => 
            array (
                'id' => 4,
                'date' => '2026-08-22',
                'nombre_heure' => '2',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:01',
                'heure_depart' => '08:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:20:06',
                'updated_at' => '2026-09-20 16:20:06',
            ),
            4 => 
            array (
                'id' => 5,
                'date' => '2026-08-29',
                'nombre_heure' => '2',
                'objectif_general' => 'OG5',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '10:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:20:45',
                'updated_at' => '2026-09-20 16:20:45',
            ),
            5 => 
            array (
                'id' => 6,
                'date' => '2026-09-05',
                'nombre_heure' => '4',
                'objectif_general' => 'OG6',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:21:27',
                'updated_at' => '2026-09-20 16:21:27',
            ),
            6 => 
            array (
                'id' => 7,
                'date' => '2026-09-12',
                'nombre_heure' => '4',
                'objectif_general' => 'OG7',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:22:49',
                'updated_at' => '2026-09-20 16:22:49',
            ),
            7 => 
            array (
                'id' => 8,
                'date' => '2026-09-15',
                'nombre_heure' => '4',
                'objectif_general' => 'OG8',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:24:02',
                'updated_at' => '2026-09-20 16:24:02',
            ),
            8 => 
            array (
                'id' => 9,
                'date' => '2026-09-17',
                'nombre_heure' => '3',
                'objectif_general' => 'OG9',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:24:41',
                'updated_at' => '2026-09-20 16:24:41',
            ),
            9 => 
            array (
                'id' => 10,
                'date' => '2026-09-19',
                'nombre_heure' => '4',
                'objectif_general' => 'OG10',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-20 16:25:14',
                'updated_at' => '2026-09-20 16:25:14',
            ),
            10 => 
            array (
                'id' => 11,
                'date' => '2026-09-01',
                'nombre_heure' => '4',
                'objectif_general' => 'OG1',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:26:29',
                'updated_at' => '2026-09-20 16:26:29',
            ),
            11 => 
            array (
                'id' => 12,
                'date' => '2026-09-02',
                'nombre_heure' => '4',
                'objectif_general' => 'OG2',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:16',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:27:07',
                'updated_at' => '2026-09-20 16:27:07',
            ),
            12 => 
            array (
                'id' => 13,
                'date' => '2026-09-03',
                'nombre_heure' => '4',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:15',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:31:01',
                'updated_at' => '2026-09-20 16:31:01',
            ),
            13 => 
            array (
                'id' => 14,
                'date' => '2026-09-03',
                'nombre_heure' => '3',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'RTYGHUYFTR',
                'heure_arrive' => '14:51',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:32:05',
                'updated_at' => '2026-09-20 16:32:05',
            ),
            14 => 
            array (
                'id' => 15,
                'date' => '2026-09-05',
                'nombre_heure' => '4',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'TERTYUIUA',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:32:51',
                'updated_at' => '2026-09-20 16:32:51',
            ),
            15 => 
            array (
                'id' => 16,
                'date' => '2026-09-05',
                'nombre_heure' => '3',
                'objectif_general' => 'OG5',
                'objectif_specific' => 'KLUUY',
                'heure_arrive' => '14:51',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 2,
                'created_at' => '2026-09-20 16:33:33',
                'updated_at' => '2026-09-20 16:33:33',
            ),
            16 => 
            array (
                'id' => 17,
                'date' => '2026-09-07',
                'nombre_heure' => '4',
                'objectif_general' => 'OG1',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:35:22',
                'updated_at' => '2026-09-20 16:35:22',
            ),
            17 => 
            array (
                'id' => 18,
                'date' => '2026-09-07',
                'nombre_heure' => '3',
                'objectif_general' => 'OG2',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:51',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:35:58',
                'updated_at' => '2026-09-20 16:35:58',
            ),
            18 => 
            array (
                'id' => 19,
                'date' => '2026-09-08',
                'nombre_heure' => '4',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:36:31',
                'updated_at' => '2026-09-20 16:36:31',
            ),
            19 => 
            array (
                'id' => 20,
                'date' => '2026-09-08',
                'nombre_heure' => '3',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:37:09',
                'updated_at' => '2026-09-20 16:37:09',
            ),
            20 => 
            array (
                'id' => 21,
                'date' => '2026-09-09',
                'nombre_heure' => '4',
                'objectif_general' => 'OG5',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:38:01',
                'updated_at' => '2026-09-20 16:38:01',
            ),
            21 => 
            array (
                'id' => 22,
                'date' => '2026-09-09',
                'nombre_heure' => '3',
                'objectif_general' => 'OG6',
                'objectif_specific' => 'TERTYUIUA',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 3,
                'created_at' => '2026-09-20 16:38:48',
                'updated_at' => '2026-09-20 16:38:48',
            ),
            22 => 
            array (
                'id' => 23,
                'date' => '2026-09-10',
                'nombre_heure' => '4',
                'objectif_general' => 'OG1',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:39:53',
                'updated_at' => '2026-09-20 16:39:53',
            ),
            23 => 
            array (
                'id' => 24,
                'date' => '2026-09-10',
                'nombre_heure' => '3',
                'objectif_general' => 'OG2',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:40:25',
                'updated_at' => '2026-09-20 16:40:25',
            ),
            24 => 
            array (
                'id' => 25,
                'date' => '2026-09-11',
                'nombre_heure' => '4',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'RTYGHUYFTR',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:41:03',
                'updated_at' => '2026-09-20 16:41:03',
            ),
            25 => 
            array (
                'id' => 26,
                'date' => '2026-09-11',
                'nombre_heure' => '3',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'TERTYUIUA',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:41:40',
                'updated_at' => '2026-09-20 16:41:40',
            ),
            26 => 
            array (
                'id' => 27,
                'date' => '2026-09-12',
                'nombre_heure' => '4',
                'objectif_general' => 'OG5',
                'objectif_specific' => 'KLUUY',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:42:20',
                'updated_at' => '2026-09-20 16:42:20',
            ),
            27 => 
            array (
                'id' => 28,
                'date' => '2026-09-12',
                'nombre_heure' => '3',
                'objectif_general' => 'OG6',
                'objectif_specific' => 'KLUUY',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:42:57',
                'updated_at' => '2026-09-20 16:42:57',
            ),
            28 => 
            array (
                'id' => 29,
                'date' => '2026-09-13',
                'nombre_heure' => '4',
                'objectif_general' => 'OG7',
                'objectif_specific' => 'KLUUY',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:43:26',
                'updated_at' => '2026-09-20 16:43:26',
            ),
            29 => 
            array (
                'id' => 30,
                'date' => '2026-09-13',
                'nombre_heure' => '3',
                'objectif_general' => 'OG8',
                'objectif_specific' => 'RTYGHUYFTR',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:44:03',
                'updated_at' => '2026-09-20 16:44:03',
            ),
            30 => 
            array (
                'id' => 31,
                'date' => '2026-09-14',
                'nombre_heure' => '4',
                'objectif_general' => 'OG9',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:45:18',
                'updated_at' => '2026-09-20 16:45:18',
            ),
            31 => 
            array (
                'id' => 32,
                'date' => '2026-09-14',
                'nombre_heure' => '3',
                'objectif_general' => 'OG10',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:51',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-20 16:46:46',
                'updated_at' => '2026-09-20 16:46:46',
            ),
            32 => 
            array (
                'id' => 33,
                'date' => '2026-08-05',
                'nombre_heure' => '4',
                'objectif_general' => 'OG1',
                'objectif_specific' => 'KLUUY',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 5,
                'created_at' => '2026-09-20 22:27:19',
                'updated_at' => '2026-09-20 22:27:19',
            ),
            33 => 
            array (
                'id' => 34,
                'date' => '2026-08-06',
                'nombre_heure' => '3',
                'objectif_general' => 'OG2',
                'objectif_specific' => 'RTYGHUYFTR',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 5,
                'created_at' => '2026-09-20 22:28:00',
                'updated_at' => '2026-09-20 22:28:00',
            ),
            34 => 
            array (
                'id' => 35,
                'date' => '2026-08-05',
                'nombre_heure' => '3',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'TEST',
                'heure_arrive' => '14:50',
                'heure_depart' => '17:50',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 5,
                'created_at' => '2026-09-20 22:28:41',
                'updated_at' => '2026-09-20 22:28:41',
            ),
            35 => 
            array (
                'id' => 36,
                'date' => '2026-08-06',
                'nombre_heure' => '4',
                'objectif_general' => 'OG4',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 5,
                'created_at' => '2026-09-20 22:29:18',
                'updated_at' => '2026-09-20 22:29:18',
            ),
            36 => 
            array (
                'id' => 37,
                'date' => '2026-09-21',
                'nombre_heure' => '2',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '10:15',
                'heure_depart' => '12:15',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 1,
                'created_at' => '2026-09-21 11:59:39',
                'updated_at' => '2026-09-21 11:59:39',
            ),
            37 => 
            array (
                'id' => 38,
                'date' => '2026-09-24',
                'nombre_heure' => '2',
                'objectif_general' => 'OG3',
                'objectif_specific' => 'AZERTYUIO',
                'heure_arrive' => '08:00',
                'heure_depart' => '10:00',
                'progression' => 'Normal',
                'enseignant_groupe_modulo_id' => 4,
                'created_at' => '2026-09-24 16:05:04',
                'updated_at' => '2026-09-24 16:05:04',
            ),
        ));
        
        
    }
}